name: Deploy Website

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy-website.yml'
      - 'website/**'
      - 'react-native-pytorch-core/src/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/deploy-website.yml'
      - 'website/**'
      - 'react-native-pytorch-core/src/**'

jobs:
  checks:
    name: Test Build ðŸ§ª
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies ðŸ§¶
        run: yarn install --frozen-lockfile
      - name: Test build website ðŸ§ª
        run: yarn build

  gh-release:
    name: Build & Deploy ðŸ”¨ ðŸš€
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies ðŸ§¶
        run: yarn install --frozen-lockfile
      - name: Build website ðŸ”¨
        run: yarn build
      - name: Deploy website ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: website/build
